language: node_js
branches:
  only:
  - development
before_install:
- npm install -g hexo
- npm install
before_script:
- git config --global user.name 'Will via Travis CI'
- git config --global user.email 'w.oliveira542@gmail.com'
- sed -i'' "s~git@github.com:woliveiras/woliveiras.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/woliveiras.github.io.git~"
  _config.yml
install:
- hexo generate
script:
- hexo deploy
env:
  global:
  - secure: JCWBtTXVFJ+aGx3aukcjFTqW6+Zmg+pYmIW0cZcVVZ/hdDf7OWuejPej/HkhNyZEmzGrgFQ6EHu2LOX+UaGC8Un7Vmp73X6n/MEYz4vxHwJGt4Xo0cMTg50glcrtOSr1tIPfDiw3IKwcUQk2HOU4spCo4xBIjZflAvet3R5lY0EJVEaLPRfUPZArujr61VcOJHdGUNJ47T27Yk0NEFuLd7K/D2rpe4gOiPdrdSEijmVE2Rdhsz+Ymn3vDt4mABz8bnJibwhpj9GcXebMWRsKfLd+8cwUQ77bDKR4CeJFYs0Pdrte6IqSvwHkhT66bYeHUSEsltmJOW59g5bUS4SO1STy0p9LG5ZLfAUo+9Hu6vL+KNEgNnbQl8jq5xR1gwpBElB/Omx3U9Z8BHQaNdiLSzCkT+1zibdRwj/F/3LvdmZN2bt4rBu334lsXWZnBs8w8i4iSAAnXbC1DgWEgxIOUE6wuwQrFbMcZ9hc0NUp8d+F6MlXSWM2mL0sAiy1nl6hZpuXTy7BHfXux71oaDxTGavbibBzSACdnvHEqkNlwiDRiAO0X0Fc18L0NdkEJGNGl4LUubmQgq6sKTMcCnVNEaw/A3QETU4RBXYOiIEwn12vNQV/BK+ROWuY0KKoxmfh8JN04GHFb9Yrnu61FHK/VjB8Gzz51+20JnZvx+IvDqI=
  - secure: qRJ9nKhK6/glCIpj8IiZu6cjhfWYrRVHWkcK51J0nVYGu7+tORh4nCxF165N605ViOvWbUhqO/AhdZT6IKcQgUkJng3NKwxotwjOgXhkIMh70WU0ajarAcJkgD3gonFVPnKeGX8n+CNAcotRuniI5IA5zU7dUMwCE7l6kx4o7zLVlak5HnKO1T9nb4swLGn9+WHI+SN3I8FLOp+u+Jn03ipe2UsYdKJzLXy+cMKN8ur9tLnRVHUySqi7RlUnANIfmJIChgcOhLsMxK4DA0Gh0NyMI8Kext5iFU/eFlYGs1psSowubyEuTgZ5TJp2SyGf1pFRmucStIyCr7toEBXobBceltBZFUNe1asfMh5Ip73sUVzCvnEIv6gBRlwT9Y0b65EJbRdXg7eg03KVF5R0SfuDWy4N3CZJ6EgNxtfj0fkS0m0ZBuUEp2Z+mc7Ue3xiCmWeeX3U0HwWndC+1O+DyiQ1OrMe4pZnEjmSu607E3JdWe9Iwt6gtsmS+y3/uv8nQTQMyOFuThoOCy5dWDh27+IUUrS6+RwD9QG57Xtv70LewUHAKjo/cAv6RpCIqnvs25P04ud0EeVpDOfluLMgS2eEo027IzgvsUyiL2nTEXZIwst/2BpWs9xpCKi+VmMEiT/raBNP9Ro1xhaJmj/akG3ymVt7ZKl4snYxsZtySVw=
