# Header
menu:
  Home: /
  Sobre: /about
  Colabore: /colabore-comigo
rss: /atom.xml

# Content
excerpt_link: Continue a leitura...
fancybox: true

# Miscellaneous
google_analytics: UA-25964646-1
favicon: img/favicon.png
twitter: w_oliveiras
